services:

  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mapyeugau110418
      MYSQL_DATABASE: auth_db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -pmapyeugau110418 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 20s


  eureka-server:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_INSTANCE_HOSTNAME: eureka-server
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost:8761/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_APPLICATION_NAME: config-server
      SERVER_PORT: 8888
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/ThaiNgocPhat/Config_Repo
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - my-network
    healthcheck:
      test: curl --fail http://localhost:8888/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 10

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - my-network

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
